version: '3.8'

services:
  school-web:
    image: httpd:2.4
    container_name: apache-http
    ports:
      - "48080:80"
    volumes:
      - ./infra/apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - work_network

  school-app:
    image: tomcat:9.0
    container_name: apcache-tomcat
    environment:
      - CATALINA_OPTS=-Dajp.port=8009
    volumes:
      - ./infra/tomcat/conf/server.xml:/usr/local/tomcat/conf/server.xml
    networks:
      - work_network

  school-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "43306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fE3SzFrcztj
      MYSQL_DATABASE: schooldb
      MYSQL_USER: portal_user
      MYSQL_PASSWORD: Hw6GPb8R
      TZ: 'Asia/Tokyo'
    networks:
      - work_network
    volumes:
        - ./infra/mysql/data:/var/lib/mysql
        - ./infra/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
        - ./infra/mysql/script:/docker-entrypoint-initdb.d 

networks:
  work_network:
    driver: bridge
